---

- name: blackbox - demo
  hosts: all
  sudo: yes

  vars:
    blackbox_path: /opt/blackbox

  tasks:
    - name: Install packages
      apt:
        pkg: "{{ item }}"
        state: installed
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - git
        - vim-nox

    - name: BlackBox | install
      git:
        repo: https://github.com/StackExchange/blackbox.git
        dest: "{{ blackbox_path}}"
        version: production
        accept_hostkey: yes

    - name: BlackBox | add to path
      shell: echo '#!/bin/bash\nPATH="${PATH}:{{ blackbox_path }}/bin"' > /etc/profile.d/blackbox.sh

    - name: Demo | clone repository
      sudo: no
      git:
        repo: https://github.com/jacoelho/blackbox-demo.git
        dest: /home/vagrant/blackbox-demo
        accept_hostkey: yes
